try-django-django/django/blog/urls.py
from django.urls import path

from .views import (
	# create_view,
	# delete_view,
	# detail_view,
	# list_view,
	# update_view,
	ArticleCreateView,
	ArticleDeleteView,
	ArticleDetailView,
	ArticleListView,
	ArticleUpdateView,
)

app_name = "blog"
urlpatterns = [
	### Function based views ###
	# path("list/", list_view, name="list"),
	# path("detail/<int:identifier>/", detail_view, name="detail"),
	# path("create/", create_view, name="create"),
	# path("update/<int:identifier>/", update_view, name="update"),
	# path("delete/<int:identifier>/", delete_view, name="delete"),
	### Class based views ###
	path("list/", ArticleListView.as_view(), name="list"),
	path("detail/<int:identifier>/", ArticleDetailView.as_view(), name="detail"),
	path("create/", ArticleCreateView.as_view(), name="create"),
	path("update/<int:identifier>/", ArticleUpdateView.as_view(), name="update"),
	path("delete/<int:identifier>/", ArticleDeleteView.as_view(), name="delete"),
]

try-django-django/django/products/urls.py
from django.urls import path

from .views import (
	create_view,
	delete_view,
	detail_view,
	list_view,
	update_view,
)

app_name = "products"
urlpatterns = [
	# path("detail/", detail_view, name="detail"),
	path("detail/<int:identifier>/", detail_view, name="detail"),
	path("create/", create_view, name="create"),
	path("delete/<int:identifier>/", delete_view, name="delete"),
	path("list/", list_view, name="list"),
	path("update/<int:identifier>/", update_view, name="update"),
]

try-django-django/django/products/models.py
from django.db import models
from django.urls import reverse


class Product(models.Model):
	title = models.CharField(max_length=120)
	description = models.TextField(blank=True, null=True)
	price = models.DecimalField(max_digits=16, decimal_places=2)
	summary = models.TextField()
	featured = models.BooleanField(default=False)

	def get_absolute_url(self):
		# return self.id
		return reverse("products:detail", kwargs={"identifier": self.id})

try-django-django/django/products/forms.py
from django import forms

from .models import Product


class ProductForm(forms.ModelForm):
	title = forms.CharField(
		max_length=120,
		label="Item Title:",
		widget=forms.TextInput(
			attrs={
				"placeholder": "Title",
				"autofocus": True,
			}
		),
	)

	class Meta:
		model = Product
		fields = [
			"title",
			# "description",
			"price",
			"summary",
			# "featured",
		]

	def clean_title(self, *arg, **kwargs):
		title = self.cleaned_data.get("title")
		if not "item" in title:
			raise forms.ValidationError("Title requires 'item' prefix")
		return title


class RawProductForm(forms.Form):
	title = forms.CharField(
		max_length=120,
		label="Item Title:",
		widget=forms.TextInput(
			attrs={
				"placeholder": "Title",
			}
		),
	)
	# description = forms.CharField(required=False, widget=forms.Textarea())
	price = forms.DecimalField(max_digits=16, decimal_places=2)
	summary = forms.CharField(
		widget=forms.Textarea(
			attrs={
				"id": "summary-textarea",
				"class": "bg-grey-100",
				"rows": 5,
				"cols": 25,
			}
		)
	)
	# featured = forms.BooleanField(required=False)

try-django-django/django/products/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import ProductForm, RawProductForm
from .models import Product


def detail_view(request, identifier, *args, **kwargs):
	# try:
	# 	product = Product.objects.get(id=identifier)
	# except Product.DoesNotExist:
	# 	raise Http404

	context = {
		# "product": Product.objects.get(id=identifier),
		# "product": product,
		"product": get_object_or_404(Product, id=identifier),
	}

	return render(request, "products/product_detail.html", context)


# def create_view(request, *args, **kwargs):
# 	context = {
# 		"title": "new product",
# 		"form": RawProductForm(request.POST or None),
# 	}

# 	if context["form"].is_valid():
# 		print(context["form"].cleaned_data)

# 		Product.objects.create(**context["form"].cleaned_data)
# 		# context["form"] = RawProductForm(None)
# 		return redirect(reverse("products:list"))
# 	else:
# 		print(context["form"].errors)

# 	return render(request, "products/product_create.html", context)


def create_view(request, *args, **kwargs):
	# if request.method == "GET":
	# 	print(request.GET)
	# elif request.method == "POST":
	# 	print(request.POST)

	# instance = Product.objects.get(id=1)

	initial = {
		"title": "item ",
		"summary": "Item ",
	}

	context = {
		"title": "new product",
		# "form": ProductForm(request.POST or None, instance=instance),
		"form": ProductForm(request.POST or None, initial=initial),
	}

	if context["form"].is_valid():
		context["form"].save()
		# context["form"] = ProductForm(None)
		return redirect(reverse("products:list"))

	return render(request, "products/product_create.html", context)


def update_view(request, identifier, *args, **kwargs):
	instance = get_object_or_404(Product, id=identifier)

	context = {
		"product": instance,
		"form": ProductForm(request.POST or None, instance=instance),
	}

	if request.method == "POST" and context["form"].is_valid():
		context["form"].save()
		# context["form"] = ProductForm(None)
		return redirect(reverse("products:detail", kwargs={"identifier": instance.id}))

	return render(request, "products/product_update.html", context)


def delete_view(request, identifier, *args, **kwargs):
	context = {
		"product": get_object_or_404(Product, id=identifier),
	}

	if request.method == "POST":
		context["product"].delete()
		return redirect(reverse("products:list"))

	return render(request, "products/product_delete.html", context)


def list_view(request, *args, **kwargs):
	context = {
		"title": "products",
		"object_list": Product.objects.all(),
	}

	return render(request, "products/product_list.html", context)

try-django-django/django/products/templates/products/product_create.html
{% extends "base.html" %}

{% block title %}{{ title|capfirst }} - {% endblock title %}

{% block content %}
	<form action="." method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Save">
			<a href="{% url 'products:list' %}">Cancel</a>
	</form>
{% endblock content %}

try-django-django/django/products/templates/products/product_delete.html
{% extends "base.html" %}

{% block title %}{{ product.title|capfirst }} - {% endblock title %}

{% block content %}
	<form action="." method="POST">
		{% csrf_token %}
		<h3>Do you want to remove {{ product.title }}?</h3>
		<p>
			<input type="submit" value="Yes">
			{# <a href="../">No</a> #}
			<a href="{% url 'products:detail' product.id %}">No</a>
		</p>
	</form>
{% endblock content %}

try-django-django/django/products/templates/products/product_detail.html
{% extends "base.html" %}

{% block title %}{{ product.title|capfirst }} - {% endblock title %}

{% block content %}
	<p>
		<a href="{% url 'products:list' %}">
			Back to list
		</a>
	</p>
	<p>
		Name: {{ product.title|capfirst }}
	</p>
	<p>
		Price: ${{ product.price }}
	</p>
	<p>
		Description:
		<br>
		{% if product.description %}
			{{ product.description }}
		{% else %}
			No description available
		{% endif %}
	</p>
	{% if user.is_staff %}
		<p>
			<a href="{% url 'products:update' product.id %}">
				Update item
			</a>
			|
			<a href="{% url 'products:delete' product.id %}">
				Delete item
			</a>
		</p>
	{% endif %}
{% endblock content %}

try-django-django/django/products/templates/products/product_list.html
{% extends "base.html" %}

{% block title %}{{ title|capfirst }} - {% endblock title %}

{% block content %}
	<p>
		<a href="{% url 'products:create' %}">New product</a>
	</p>
	{% if object_list|length %}
		{% for instance in object_list %}
			<p>
				<a href="{{ instance.get_absolute_url }}">
					Name: {{ instance.title|capfirst }}
				</a>
			</p>
			<p>
				Price: ${{ instance.price }}
			</p>
			<p>
				{{ instance.summary }}
			</p>
			{% if forloop.counter != object_list|length %}
				<hr>
			{% endif %}
		{% endfor %}
	{% else %}
		<p>
			No products added yet
		</p>
	{% endif %}
{% endblock content %}

try-django-django/django/products/templates/products/product_update.html
{% extends "base.html" %}

{% block title %}{{ product.title|capfirst }} - {% endblock title %}

{% block content %}
	<form action="." method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Save">
		<a href="{% url 'products:detail' product.id %}">Cancel</a>
	</form>
{% endblock content %}